@startuml
title 基于GitHub的实验管理平台--登录的流程图
start
:输入用户名;
:输入密码;
:选择角色（学生、老师、管理员）;
:登录;
if(用户名是否存在？) then(是)
    if(密码是否正确？) then(是)
        :登录成功;
        :进入首页;
     else(否)
        :提示用户输入错误;
        :重新输入;
     endif;
else(否)
    :提示用户账号不存在;
    :重新输入;
endif;
:登录流程结束;
stop;
@enduml