@startuml
title 基于GitHub的实验管理平台--评定成绩用例的流程图
start
:老师评定一个学生实验成绩;

if(该老师是否已登录？) then(是)
    :点击老师学生列表后的成绩评定按钮;
    :获取学生已评定成绩所有信息;
    :录入并提交新实验成绩和评语;
    :数据库存储信息;
else(否)
    :重新登录;
endif;
:流程结束;

stop;
@enduml