@startuml

class 登陆{
    账号
    密码
    身份
    --
    End of class
}

class 读者 {
    账号
    姓名
    年龄
    身份证号
    --
    - 图书预定
    - 图书归还
    - 取消预定
    + 查看图书
    + 个人信息修改
    - 借书记录查询
    + 个人信用查询
    --
    End of class
}

class 图书管理员 {
    职工号
    姓名
    入职时间
    职位
    --
    - 图书预定管理
    - 借书登记
    - 还书登记
    - 图书增、删、改、查
    + 个人信息修改
    --
    End of class
}
class 系统管理员{
    账号
    姓名
    --
    # 系统维护
    - 账号管理（增、删、改、查）
    - 权限管理
    - 公告
    --
    End of class
}
class 图书{
    ISBN
    书名
    出版社
    作者
    价格
    简介
    馆藏数量
    可借数量
    内容
    --
    End of class
}

class 馆藏目录{
    书目
    备注
    --
    End of class
}

class 借书记录{
    借书日期
    应还日期
    归还日期
    备注
    --
    End of class
}

class 预定记录{
    预定日期
    备注
    --
    End of class
}

class 逾期记录{
    预期时间
    备注
    --
    End of class
}

class 还书{
    还书时间
    备注
}

class 公告{
    公告内容
    备注
    --
    End of class
}

读者 "n"*-->"1"登陆
图书管理员 "1..10"*---> "1"登陆
系统管理员 "1,2,3"*--=-> "1"登陆


系统管理员 "1"-- "1..10"图书管理员 :Association
系统管理员 "1"-- "n"读者 :Association
系统管理员 "1"*-- "n"公告 :Association

图书管理员 "1"-- "n"图书 :Association
图书管理员 "1"-- "n"借书记录 :登记 :Contains
图书管理员 "1"-- "n"还书 :登记 :Contains
图书管理员 "1"-- "n"预定记录 :Association


馆藏目录 "1"*--- "1..n"图书 :Contains
图书 "1"--  "n"预定记录 :Association
图书 "1"-- "n"借书记录 :Association

读者 "1"--"n"预定记录 :Contains
读者 "1"-- "n"借书记录 :Contains
读者 "1"-- "n"还书

借书记录 "1"-- "0..1"逾期记录

@endum