@startuml

object 登陆{
    name = name
    password = password
    —————————————
    + void user(name,password)
    ......
}

object 读者{
    account = 201510514427
    姓名 = 张启恒
    年龄 = 21
    身份证号 = 1234567890213134
    借书次数 = 10
    借书记录
    预定图书
    ......
}

object 图书管理员{
    account = "201512340000"
    name = "李四"
    password = "123456"
    ......
}

object 系统管理员{
    account = "2015000111"
    name = "张三"
    password = "123456"
    ......
}

object 图书{
    ISBN = 98984284529339
    书名 = 十万个为什么
    出版社 = 清华大学出版社
    作者 = 余小小
    价格 = 99.00
    可借数量 = 50
    ......
}

object 馆藏目录{
    书目列表 ：《十万个为什么》
    ......
 }

object 借书记录{
    借书日期 = 2018-01-02
    应还日期 = 2018-03-01
    还书日期 = 2018-02-24
    借书次数 = 20
    ......
}

object 预定记录{
    预定日期：2018-01-01
    状态：可借
    截至日期：2018-01-07
    ......
}

object 逾期记录{
    逾期状态：是
    逾期时间：2018-05-01
    逾期天数：30
    ......
}

object 还书{
    ISBN = 98984284529339
    书名 = 十万个为什么
    还书时间 = 2018-02-24
    状态 = 已还
    ......
}

object 公告{
    标题 = 新书上架
    内容 = 图书馆将于2018-05-01上架30余款新书，其中有15本美国原著大作、国内精选论文、计算机类等新书。敬请广大师生借阅。
    时间 = 2018-03-23
    ......
}

读者 --> 登陆
图书管理员 ---> 登陆
系统管理员 ---> 登陆

系统管理员 --> 公告 :公告更新、删除
系统管理员 --> 图书管理员 :账号管理、权限分配
系统管理员 --> 读者 :账号管理（增删查改）

图书管理员 -- 图书 :图书管理（增删查改）
图书管理员 <-- 借书记录 :登记借书记录
图书管理员 <-- 还书 :删除借书记录
图书管理员 -- 预定记录 :查看预定记录


馆藏目录 ---> 图书
图书 --  预定记录 :系统自动判断读者是否可借书
图书 --> 借书记录 :可查询图书借阅记录

读者 --> 预定记录 :预定图书、查询记录
读者 --> 借书记录 :查询借书记录
读者 --> 还书 :归还图书

借书记录 --> 逾期记录 :系统判断是否逾期

@endum