@startuml

class 管理员 {
    ID
    管理员名
    密码
    角色
    电话
    照片
    --set和get--
    ...
    --
    End of class
}

class 图书管理员 {
    角色
    --
    End of class
}
class 系统管理员{
    角色
    --
    End of class
}

class 读者 {
    账号
    姓名
    密码
    性别
    出生日期
    角色
    所属学院
    专业
    借书数量
    照片
    电话
    --set和get--
    ...
    --
    End of class
}

class 馆藏目录{
    ID
    ISBN
    书名
    语言
    国家
    种类
    种类细分
    其它
    --get And set--
    ...
    --
    End of class
}
class 图书{
    ISBN
    书名
    出版社
    作者
    价格
    馆藏数量
    可借数量
    借出总次数
    内容简介
    照片
    --set和get--
    ...
    --
    End of class
}

class 借书记录{
    流水号
    ISBN
    读者ID
    书名
    借书日期
    归还日期
    是否续借
    借书时长
    是否归还
    是否逾期
    逾期时长
    --set和get--
    ...
    --
    End of class
}

class 预定记录{
    流水号
    读者ID
    ISBN
    预定日期
    时长
    是否取消预定
    --set和get--
    ...
    --
    End of class
}

class 逾期记录{
    流水号
    ISBN
    读者ID
    书名
    逾期时间
    归还时间
    逾期时长
    备注
    --set和get--
    ...
    --
    End of class
}

class 图书操作日志{
    ID
    动作
    细节
    创建时间
    实体ID
    实体名称
    --set和get--
    ...
    --
    End of class
}

class 公告{
    ID
    公告内容
    开始时间
    结束时间
    备注
    --set和get--
    ...
    --
    End of class
}

管理员 <- 系统管理员
管理员 <- 图书管理员

系统管理员 "1"-- "1..10"图书管理员 :Association
系统管理员 "1"- "n"读者 :Association
系统管理员 "1"*- "n"公告 :Association

图书管理员 "1"-- "n"图书 :Association
图书管理员 "1"-- "n"图书操作日志 :Association

馆藏目录 "1"<- "n"图书 :Contains

图书 "1"--  "n"预定记录 :Association
图书 "1"-- "n"借书记录 :Association
图书 "1"-- "n" "图书操作日志" :Association
图书 "1"-- "0..2"逾期记录 :Contains

读者 "1"--"n"预定记录 :Contains
读者 "1"-- "n"借书记录 :Contains
读者 "1"-- "0..2"逾期记录 :Contains

@endum