@startuml
start
:输入账号;
:输入密码;
:登录;
:选择读者或管理员身份;
if(账号是否存在？) then(是)
    if(账号密码是否正确？) then(是)
        :登录成功;
        :进入首页;
     else(否)
        :提示用户账号密码错误;
        :重新登录;
     endif;
else(否)
    :提示用户账号不存在;
    :重新登录;
endif;
:登录流程结束;
stop;
@enduml