@startuml

actor 用户 as user
participant Login登录页面 as l
participant Users as u
database 数据库 as db

user -> l: 1.进入登录页面
l -> u: 2.输入用户名和密码
u --> u: 3.检查用户输入信息
u -->user: 4.输入格式错误，重新输入
u -> db: 5.输入信息正确，提交数据库匹配
db --> db: 6.数据库检测
db --> user: 7.信息匹配失败，用户名不存在或密码不正确，请重新输入
db -> user: 8.信息匹配成功，提示登录成功


@enduml